file_format: "1"
id: sweet16
name: 1upkeyboards Sweet 16 V1
type: shield
url: https://1upkeyboards.com/shop/keyboard-kits/macro-pads/sweet-16-macro-pad-black/
requires: [pro_micro]
features:
  - keys
